### ISSUE TITLE
[ BUG ] on falconpy\_payload\_generic.py - AttributeError: 'dict' object has no attribute 'split'

### ISSUE THREAD

**Issue by NSH531** [CrowdStrike/falconpy#768]
screenshot:
![image](https://user-images.githubusercontent.com/5903577/188302355-24b1e5cd-9a2e-44f2-957e-f8cbbdd55eeb.png)

stacktrace:
```

   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://localhost:3448 (Press CTRL+C to quit)
[2022-09-04 10:16:38,192] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2077, in wsgi_app
  File "flask\app.py", line 1525, in full_dispatch_request
  File "flask\app.py", line 1523, in full_dispatch_request
  File "flask\app.py", line 1509, in dispatch_request
  File "gimlaot\views.py", line 32, in Index
  File "falconpy\_util.py", line 144, in factory
  File "falconpy\detects.py", line 218, in get_detect_summaries
  **File "falconpy\_payload\_generic.py", line 62, in generic_payload_list**
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by jshcodes** [comment]
Moving to discussion board.
